#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestApp2.Android.Resource", IsApplication=true)]

namespace TestApp2.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cardBackgroundColor = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cardCornerRadius = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cardElevation = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cardMaxElevation = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int cardUseCompatPadding = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int cardViewStyle = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int contentPadding = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int contentPaddingBottom = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int contentPaddingLeft = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int contentPaddingRight = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int contentPaddingTop = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int coordinatorLayoutStyle = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int fastScrollEnabled = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int fastScrollHorizontalThumbDrawable = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int fastScrollHorizontalTrackDrawable = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int fastScrollVerticalThumbDrawable = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int fastScrollVerticalTrackDrawable = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int font = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int fontProviderAuthority = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int fontProviderCerts = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int fontProviderFetchStrategy = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int fontProviderFetchTimeout = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int fontProviderPackage = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int fontProviderQuery = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int fontStyle = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int fontVariationSettings = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int fontWeight = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int keylines = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int layoutManager = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int layout_anchor = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int layout_anchorGravity = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int layout_behavior = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int layout_dodgeInsetEdges = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int layout_insetEdge = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int layout_keyline = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int reverseLayout = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int spanCount = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int stackFromEnd = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int statusBarBackground = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int ttcIndex = 2130772009;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int cardview_dark_background = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int cardview_light_background = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int cardview_shadow_end_color = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cardview_shadow_start_color = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int notification_action_color_filter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int notification_icon_bg_color = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int notification_material_background_media_default_color = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int primary_text_default_material_dark = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int ripple_material_light = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int secondary_text_default_material_dark = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int secondary_text_default_material_light = 2130837514;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int cardview_compat_inset_shadow = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int cardview_default_elevation = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int cardview_default_radius = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_inset_horizontal_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_button_inset_vertical_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_button_padding_horizontal_material = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_button_padding_vertical_material = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int compat_control_corner_material = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int compat_notification_large_icon_max_height = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int compat_notification_large_icon_max_width = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int fastscroll_default_thickness = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int fastscroll_margin = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int fastscroll_minimum_range = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int item_touch_helper_swipe_escape_velocity = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_action_icon_size = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_action_text_size = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_big_circle_margin = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_content_margin_start = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_large_icon_height = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_large_icon_width = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int notification_main_column_padding_top = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int notification_media_narrow_margin = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int notification_right_icon_size = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int notification_right_side_padding_top = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int notification_small_icon_background_padding = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int notification_small_icon_size_as_large = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int notification_subtext_size = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int notification_top_pad = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int notification_top_pad_large_text = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int subtitle_corner_radius = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int subtitle_outline_width = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int subtitle_shadow_offset = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int subtitle_shadow_radius = 2130903074;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int notification_action_background = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int notification_bg = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int notification_bg_low = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int notification_bg_low_normal = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int notification_bg_low_pressed = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_bg_normal = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_bg_normal_pressed = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_icon_background = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_template_icon_bg = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_template_icon_low_bg = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_tile_bg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notify_panel_notification_icon_bg = 2130968587;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action0 = 2131034112;
			
			// aapt resource value: 0x7F050005
			public const int actions = 2131034117;
			
			// aapt resource value: 0x7F050001
			public const int action_container = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int action_divider = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int action_image = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int action_text = 2131034116;
			
			// aapt resource value: 0x7F050006
			public const int all = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int async = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int blocking = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int bottom = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int cancel_action = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int center = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int center_horizontal = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int center_vertical = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int chronometer = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int clickable = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int clip_horizontal = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int clip_vertical = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int description = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int end = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int end_padder = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int fill = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int fill_horizontal = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int fill_vertical = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int forever = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int icon = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int icon_group = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int image = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int info = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int italic = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int item_touch_helper_previous_elevation = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int left = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int line1 = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int line3 = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int media_actions = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int none = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int normal = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int notification_background = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int notification_main_column = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int notification_main_column_container = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int progressBar = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int recyclerView = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int right = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int right_icon = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int right_side = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int start = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int status_bar_latest_event_content = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int tag_transition_group = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int tag_unhandled_key_event_manager = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int tag_unhandled_key_listeners = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int text = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int text2 = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int time = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int title = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int top = 2131034166;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int status_bar_notification_info_maxnum = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int activity_main = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int activity_second = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int item_fact_list = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int notification_action = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int notification_action_tombstone = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_media_action = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_media_cancel_action = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_template_big_media = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_template_big_media_custom = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_big_media_narrow = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_big_media_narrow_custom = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int notification_template_custom_big = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int notification_template_icon_group = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int notification_template_lines_media = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int notification_template_media = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int notification_template_media_custom = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int notification_template_part_chronometer = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int notification_template_part_time = 2131165201;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int hello = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int status_bar_notification_info_overflow = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int Base_CardView = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int CardView = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int CardView_Dark = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int CardView_Light = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int TextAppearance_Compat_Notification = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int TextAppearance_Compat_Notification_Info = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int TextAppearance_Compat_Notification_Info_Media = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int TextAppearance_Compat_Notification_Line2 = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int TextAppearance_Compat_Notification_Media = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int TextAppearance_Compat_Notification_Time = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int TextAppearance_Compat_Notification_Time_Media = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int TextAppearance_Compat_Notification_Title = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int TextAppearance_Compat_Notification_Title_Media = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int Widget_Compat_NotificationActionContainer = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int Widget_Compat_NotificationActionText = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int Widget_Support_CoordinatorLayout = 2131296272;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x101013F,0x1010140,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C }
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 6
			public const int CardView_cardPreventCornerOverlap = 6;
			
			// aapt resource value: 7
			public const int CardView_cardUseCompatPadding = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingBottom = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingLeft = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingRight = 11;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingTop = 12;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F01001D,0x7F010028 }
			public static int[] CoordinatorLayout = new int[] {
					2130771997,
					2130772008};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010023,0x7F010024 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019 }
			public static int[] FontFamily = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010013,0x7F01001A,0x7F01001B,0x7F01001C,0x7F010029 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771987,
					2130771994,
					2130771995,
					2130771996,
					2130772009};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x10100C4,0x10100F1,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F01001E,0x7F010025,0x7F010026,0x7F010027 }
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771998,
					2130772005,
					2130772006,
					2130772007};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_fastScrollEnabled = 2;
			
			// aapt resource value: 3
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 3;
			
			// aapt resource value: 4
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 4;
			
			// aapt resource value: 5
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 5;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 6;
			
			// aapt resource value: 7
			public const int RecyclerView_layoutManager = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_reverseLayout = 8;
			
			// aapt resource value: 9
			public const int RecyclerView_spanCount = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_stackFromEnd = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
